import Head from "next/head";

// import { Inter } from '@next/font/google'
import styles from "@/styles/Home.module.css";
import { PostComponent } from "@/PostComponent/IPostCard";
import { useState } from "react";
import { postArrays } from "@/Interface/postInterface";
import DrawerAppBar from "@/AppBarComponents/appBar";
import { Container, Typography } from "@mui/material";
import { Stack, Box } from "@mui/material";
import { PostWithComment } from "@/CommentComponent/CommentsTab";
import PermanentDrawerLeft from "@/Drawer/Drawer";
// import { Nunito_Sans } from "next/font/google";

// const nunito_Sans = Nunito_Sans({ subsets: ["latin"] });
export default function Home() {
  // const [post, setPost] = useState<Array>(postArrays)

  const [show,setShow] = useState(false)



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com"/> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:opsz,wght@6..12,200;6..12,300;6..12,400;6..12,500&display=swap" rel="stylesheet"/>       */}
        </Head>

      {/* <Container fixed> */}
      {/* <div> */}
        {/* <DrawerAppBar /> */}
       <PermanentDrawerLeft/>
        <Box
          sx={{
            display: "flex",
            // justifyContent: "left",
            width: "83%",
            flexDirection: "row",
            ml: "250px",
            px:'10px',
            // alignItems: "center",
            // paddingLeft: "200px",
            mt: "90px",
            border: "red 2px solid",
            // marginLeft: "40px"
            gap:'10px'
          }}
        >
          <Stack
            sx={{
              flexGrow: 1,
              maxWidth: "900px",
              border: "red 2px solid",
              gap: "20px",
              // pl: { sm: "", md: "40px" },
              // pr: { sm: "", md: "24px" },
            }}
          >
            {postArrays.map((item) => {
              return <Box onClick={()=>setShow(val=>!val)} minHeight="220px" border='1px solid blue'>
                <Typography> {item.messageTitle} </Typography>
              </Box>
            })}
          </Stack>
          { show ?  <Box minHeight="90vh" border="1px solid red">

          </Box>: null}
          {/* <PostWithComment /> */}
        </Box>
        {/* </div> */}
      {/* </Container> */}
    </>
  );
}
